const PLAY_URL='https://play.google.com/store/apps/details?id=sg.claimproof.mobile';
const steps=[['01','TRACK','Record work time, workday details and location by project.'],['02','CAPTURE','Save photos of work in progress, completed work, defects and other site conditions.'],['03','ORGANIZE','Keep dates, notes, photos and work records together instead of scattered across apps.'],['04','REPORT','Select the records you need and export them as PDF or CSV.']];
const faq=[['What is DISPUTE?','DISPUTE is a work-record app designed to help you keep time, photos, notes and project records organized before details are forgotten or challenged.'],['Does DISPUTE provide legal advice?','No. DISPUTE is a documentation tool. It does not provide legal advice and does not guarantee the outcome of any dispute.'],['What can I record?','The app supports project-based time records, work location, photographic records with categories and notes, pay settings, and report exports.'],['Where do I subscribe?','Account creation and available subscription options are handled inside the DISPUTE Android app. The website does not process subscriptions.']];
function PlayButton({secondary=false}:{secondary?:boolean}){return <a className={'btn '+(secondary?'':'primary')} href={PLAY_URL} target="_blank" rel="noreferrer">Get DISPUTE on Google Play</a>}
export default function Home(){return <>
<nav className="nav"><div className="wrap navin"><a className="brand" href="#top">DISPUTE</a><div className="links"><a href="#how">How it works</a><a href="#product">Product</a><a href="#faq">FAQ</a><PlayButton/></div></div></nav>
<main id="top"><div className="wrap hero"><div><div className="eyebrow">Work records before disagreements become disputes</div><h1>You did the work. Keep the proof.</h1><p>Track work time, document locations, capture photos and organize project records in one place — then export the records you need when details matter.</p><div className="actions"><PlayButton/><a className="btn" href="#how">See how it works</a></div></div><div className="phone"><img src="/screens/a_001.jpg" alt="DISPUTE Time screen showing a project work record"/></div></div>
<section className="section" id="how"><div className="wrap"><div className="eyebrow">How it works</div><h2>One project. One organized record.</h2><p className="lead">DISPUTE brings the parts of a work record together so you do not have to reconstruct the story later from your camera roll, messages, notes and memory.</p><div className="grid4">{steps.map(([n,h,p])=><div className="card" key={n}><div className="num">{n}</div><h3>{h}</h3><p>{p}</p></div>)}</div></div></section>
<section className="section" id="product"><div className="wrap"><div className="eyebrow">Real product screens</div><h2>Built around the record of the work.</h2><p className="lead">The screens below come from DISPUTE itself — not fabricated product mockups.</p><div className="screens"><div><div className="phone"><img src="/screens/a_004.jpg" alt="DISPUTE recent work sessions and work location"/></div><div className="screenlabel"><strong>Time & location</strong><span>Keep project work sessions together.</span></div></div><div><div className="phone"><img src="/screens/a_005.jpg" alt="DISPUTE photo evidence screen"/></div><div className="screenlabel"><strong>Photos with context</strong><span>Classify work, completion, defects or other conditions and add notes.</span></div></div><div><div className="phone"><img src="/screens/a_007.jpg" alt="DISPUTE report export screen"/></div><div className="screenlabel"><strong>PDF & CSV reports</strong><span>Select time records and photos, then export.</span></div></div></div></div></section>
<section className="section"><div className="wrap proof"><div><div className="eyebrow">Why it matters</div><h2>Records are more useful when they stay connected.</h2><p className="lead">A photo alone may lose its context. A time entry alone does not show what happened. DISPUTE is designed to keep the project, date, work record, location, photos and notes closer together.</p></div><div className="flow">PROJECT<br/>├── <b>Time records</b><br/>├── <b>Work location</b><br/>├── <b>Work photos</b><br/>├── <b>Defects / completion</b><br/>├── <b>Notes</b><br/>└── <b>PDF / CSV report</b></div></div></section>
<section className="section"><div className="wrap proof"><div className="phone"><img src="/screens/b_003.jpg" alt="DISPUTE pay settings screen"/></div><div><div className="eyebrow">Work settings</div><h2>Record the arrangement, not just the clock.</h2><p className="lead">DISPUTE includes work and pay settings such as currency, hourly, daily or monthly arrangements, working hours and breaks, helping keep project records grounded in the way the work was agreed.</p></div></div></section>
<section className="section" id="faq"><div className="wrap"><div className="eyebrow">FAQ</div><h2>Before you download.</h2><div className="faq">{faq.map(([q,a])=><div className="card" key={q}><h3>{q}</h3><p>{a}</p></div>)}</div></div></section>
<section className="cta"><div className="wrap"><div className="eyebrow">DISPUTE for Android</div><h2>Keep the record when details matter.</h2><p className="lead" style={{margin:'0 auto 28px'}}>Create your account, view available subscription options and manage your plan inside the DISPUTE app.</p><PlayButton/></div></section>
</main><footer className="footer"><div className="wrap footin"><span>© 2026 DISPUTE. Documentation software, not legal advice.</span><div className="smalllinks"><span>Privacy</span><span>Terms</span><span>Contact</span></div></div></footer>
</>}
